image: php:latest

cache:
  paths:
    - vendor/

before_script:
  # Install Xdebug for code coverage reports
  - apt-get install php-xdebug
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

php-cs-fixer:
  script:
    - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

phpmd:
  script:
    - vendor/bin/phpmd src,tests ansi cleancode,codesize,controversial,design,naming,unusedcode --exclude src/Kernel.php

psalm:
  script:
    - vendor/bin/psalm

phpstan:
  script:
    - vendor/bin/phpstan

phpunit:
  variables:
    MUSEMENT_API_URL: https://sandbox.musement.com/api/v3
    WEATHER_API_URL: https://api.weatherapi.com/v1
    WEATHER_API_KEY: 8f6949cbe8934b1cb87235108212105
  script:
    - vendor/bin/phpunit --coverage-text --colors=never
