name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: '7.4'
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Download dependencies
        run: composer install -o --ignore-platform-reqs

      - name: Run php-cs-fixer (coding standard)
        run: ./vendor/bin/php-cs-fixer fix

      - name: Run psalm (static analysis)
        run: ./vendor/bin/psalm

      - name: Run phpunit (tests)
        run: ./vendor/bin/phpunit
